"""
RPA Bot 3: Report Bot
Generates PDF "Suspicious Transaction Report" (RBI STR format).
In production, this would be filed with the Financial Intelligence Unit (FIU-IND).
"""

import os
from datetime import datetime

REPORTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "reports")


def generate_report(transaction, case_id="N/A"):
    """
    Generate a text-based Suspicious Transaction Report.
    Uses plain text format (PDF generation requires reportlab library).

    Args:
        transaction: dict with fraud transaction details.
        case_id: str, the case ID from Bot 2.

    Returns:
        dict with report details.
    """
    os.makedirs(REPORTS_DIR, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = f"STR-{datetime.now().strftime('%Y%m%d%H%M%S')}"
    fraud_prob = transaction.get("fraud_probability", 0)

    # SHAP reasons
    shap_reasons = transaction.get("shap_explanation", [])
    reasons_text = ""
    for i, reason in enumerate(shap_reasons[:5], 1):
        direction = "INCREASES" if reason["shap_value"] > 0 else "DECREASES"
        reasons_text += f"    {i}. {reason['feature']}: {direction} fraud risk (SHAP: {reason['shap_value']:+.4f})\n"

    # Build the report content
    report_content = f"""
================================================================================
                    SUSPICIOUS TRANSACTION REPORT (STR)
                    RBI/FIU-IND Compliance Document
================================================================================

REPORT DETAILS
--------------------------------------------------------------------------------
Report ID:          {report_id}
Case Reference:     {case_id}
Generated By:       FraudGuard AI - RPA Bot 3 (Automated)
Generated At:       {timestamp}
Classification:     SUSPICIOUS TRANSACTION

TRANSACTION INFORMATION
--------------------------------------------------------------------------------
Transaction ID:     {transaction.get('id', 'N/A')}
Date & Time:        {transaction.get('timestamp', timestamp)}
Amount:             Rs {transaction.get('amount', 0):,.2f}
Merchant:           {transaction.get('merchant', 'Unknown')}
Location:           {transaction.get('city', 'Unknown')}
Card Used:          {transaction.get('card', 'N/A')}

CUSTOMER INFORMATION
--------------------------------------------------------------------------------
Customer Name:      {transaction.get('customer', 'Unknown')}
Account Status:     TEMPORARILY FROZEN

AI ANALYSIS
--------------------------------------------------------------------------------
Model Used:         XGBoost (Gradient Boosting)
Fraud Probability:  {fraud_prob * 100:.1f}%
Risk Level:         {"HIGH" if fraud_prob >= 0.7 else "MEDIUM" if fraud_prob >= 0.3 else "LOW"}
Confidence:         {"Very High" if fraud_prob >= 0.9 else "High" if fraud_prob >= 0.7 else "Moderate"}

EXPLAINABILITY (SHAP Analysis - Top Risk Factors):
{reasons_text}
RECOMMENDED ACTIONS
--------------------------------------------------------------------------------
1. Freeze customer's card pending investigation
2. Contact customer for transaction verification
3. Escalate to Senior Fraud Analyst if unresolved in 24 hours
4. File with FIU-IND if confirmed as fraud (within 7 days per RBI guidelines)

COMPLIANCE NOTES
--------------------------------------------------------------------------------
This report is generated in compliance with:
- RBI Master Direction on KYC (Know Your Customer)
- Prevention of Money Laundering Act (PMLA), 2002
- RBI Guidelines on Fraud Reporting (RBI/2024-25/XX)

Report generated automatically by FraudGuard AI system.
For queries, contact: fraud-ops@fraudguard.ai

================================================================================
                         END OF REPORT - {report_id}
================================================================================
"""

    # Save report to file
    report_filename = f"{report_id}.txt"
    report_path = os.path.join(REPORTS_DIR, report_filename)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    # Print simulation output
    print("\n" + "=" * 60)
    print("  BOT 3: REPORT BOT - STR Generated")
    print("=" * 60)
    print(f"  Report ID:   {report_id}")
    print(f"  Case Ref:    {case_id}")
    print(f"  Customer:    {transaction.get('customer', 'Unknown')}")
    print(f"  Amount:      Rs {transaction.get('amount', 0):,.2f}")
    print(f"  Fraud Score: {fraud_prob * 100:.1f}%")
    print(f"  Saved To:    {report_path}")
    print(f"  Format:      Suspicious Transaction Report (RBI STR)")
    print("=" * 60)

    return {
        "bot": "Bot 3 - Report",
        "status": "generated",
        "report_id": report_id,
        "report_path": report_path,
        "timestamp": timestamp,
    }


# Quick test
if __name__ == "__main__":
    test_txn = {
        "id": "TXN-001234",
        "customer": "Rohan Sharma",
        "amount": 45000.00,
        "merchant": "Amazon India",
        "city": "Mumbai",
        "card": "Visa ****1234",
        "fraud_probability": 0.92,
        "shap_explanation": [
            {"feature": "TransactionAmt", "shap_value": 1.32, "direction": "increases fraud risk"},
            {"feature": "card1_te", "shap_value": 0.89, "direction": "increases fraud risk"},
            {"feature": "C14", "shap_value": 1.14, "direction": "increases fraud risk"},
            {"feature": "D2", "shap_value": 0.67, "direction": "increases fraud risk"},
            {"feature": "V282", "shap_value": -0.37, "direction": "decreases fraud risk"},
        ],
    }
    result = generate_report(test_txn, case_id="CASE-0001")
    print(f"\nReport saved: {result['report_path']}")
